---
hostname: R02
vty:
  num_min: 0
  num_max: 4
  exec_timeout: 0

ospf:
  - id: 10
    rid: 2.2.2.2
    networks:
      - net: 10.131.11.0/24
        area: 0
      - net: 10.131.12.0/24
        area: 0
      - net: 10.131.13.0/24
        area: 0
    passive_int:
      default_passive: true
      int_name:
        - gig2
        - gig3
        - gig4

ospf_int:
  - int_name: Gig3
    cost: 10
    net_type: point-to-point
    priority: 10

ospf_check_rtr:
  my_areas: [0]
  my_nbr_count: 1
  should_be_asbr: false
  should_be_stub_trt: false
