---
hostname: R6
vty:
  num_min: 0
  num_max: 4
  exec_timeout: 0

ospf:
  - id: 10
    rid: 6.6.6.6
    networks:
      - net: 0.0.0.0/0
        area: 0

ospf_check_rtr:
  my_areas: [0]
  my_nbr_count: 1
  should_be_asbr: false
  should_be_stub_trt: false
